### ISSUE TITLE
今天测试成果

### ISSUE THREAD

**Issue by 19961102** [jy03078584/hpv4g#1]
[我今天试了下其他地区的，前一分钟都是提示排队人数较多，之后就提示错误了，我这边找了一份js的脚本，目前遇到了一些运行环境上的错误，如果老哥懂的话可以邮箱互相研究下
![6dbdd2e12d575d82b0d6c0309b5c407](https://user-images.githubusercontent.com/65450170/95678160-773c3d00-0bfd-11eb-837b-2bc52241a42c.png)

**Comment by jy03078584** [comment]
@19961102 
报错这个是个bug哈 单独把这个脚本重构的时候没给默认`最大线程数`  谢谢老哥
JS我不是很了解哈~Sorry

**Comment by 19961102** [comment]
确实有改变，但是我还没找到原因，用你的和另外一个都一直提示排队人数过多
