### ISSUE TITLE
老哥能把用法写详细点吗，一直运行不了T T

### ISSUE THREAD

**Issue by zj903957973** [jy03078584/hpv4g#2]

**Comment by jy03078584** [comment]
老哥 抓包获取参数了直接运行
- 用`fiddler`这类抓包工具对`約苗`微信小程序抓包获取2个必须的参数`tk` `cookie`
<img width="509" alt="2" src="https://user-images.githubusercontent.com/7719370/99932763-06f41000-2d94-11eb-80b6-3c76b112db6d.png">

- 键入`tk cookie`直接执行运行文件 `hpv4g.py`或`scan_vaccine.py`
<img width="889" alt="1" src="https://user-images.githubusercontent.com/7719370/99932751-f9d72100-2d93-11eb-8840-1110e0be3136.png">

**Comment by zj903957973** [comment]
> 老哥抓包获取参数了直接运行
> 
> * 用`fiddler`种类抓包工具对`約苗`微信小程序抓包获取2个必须的参数`tk` `cookie`
> 
> <img alt="2" width="509" src="https://user-images.githubusercontent.com/7719370/99932763-06f41000-2d94-11eb-80b6-3c76b112db6d.png">
> 
> * 键入直接`tk cookie`执行运行文件`hpv4g.py`或`scan_vaccine.py`
> 
> <img alt="1个" width="889" src="https://user-images.githubusercontent.com/7719370/99932751-f9d72100-2d93-11eb-8840-1110e0be3136.png">

好的，非常感谢！
