### ISSUE TITLE
程序报错

### ISSUE THREAD

**Issue by cycycy122** [jy03078584/hpv4g#3]
代码提示格式问题，这两个地方得 := 应该都是 == 吧
![图像_2020-11-24_135315](https://user-images.githubusercontent.com/74948739/100054114-66b5ee00-2e5c-11eb-8f19-f0cdf052e8d3.png)
![图像_2020-11-24_135330](https://user-images.githubusercontent.com/74948739/100054128-6fa6bf80-2e5c-11eb-942e-88606b29b8c6.png)

**Comment by cycycy122** [comment]
![image](https://user-images.githubusercontent.com/74948739/100054170-85b48000-2e5c-11eb-810b-54390f0ece55.png)

**Comment by jy03078584** [comment]
这不是格式问题
是你`python`版本问题
这是 python3.8后的 **`海象运算符`**
ref:https://docs.python.org/3/whatsnew/3.8.html#assignment-expressions
<img width="541" alt="hx_20201124141340" src="https://user-images.githubusercontent.com/7719370/100055748-4f2c3480-2e5f-11eb-9c3e-78a3d5248150.png">
