### ISSUE TITLE
这种情况是代理ip的问题吗？

### ISSUE THREAD

**Issue by zj903957973** [jy03078584/hpv4g#4]
URL: https://miaomiao. scmttec. com/secki11/secki11/list. do ERROR: HTTPSConnectionPool(host=' miaomiao. scmttec. com, port=443): Max retries exceeded with ur1:/secki11/secki
11/list. do? offset=0& limit=10& regionCode=5101(Caused by SSLError(SSLError(1,'[ SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1108)')))

**Comment by zj903957973** [comment]
![QQ截图20201126104209](https://user-images.githubusercontent.com/62865487/100302044-6d677100-2fd4-11eb-8d89-8234ba016e95.png)

**Comment by jy03078584** [comment]
报错的日志看是SSL验证失败
你有改过代码上的`verify=False`参数么

**Comment by zj903957973** [comment]
> 报错的日志看是SSL验证失败
> 你有改过代码上的`verify=False`参数么

没改

**Comment by jy03078584** [comment]
> > 报错的日志看是SSL验证失败
> > 你有改过代码上的`verify=False`参数么
> 
> 没改

`scmttec.com/secki11/secki11/list. do` 这个接口不会走代理IP
应该是本地SSL Client 证书的问题

**Comment by zj903957973** [comment]
> > > 报错的日志看是SSL验证失败
> > > 你有改过代码上的`verify=False`参数么
> > 
> > 
> > 没改
> 
> `scmttec.com/secki11/secki11/list. do`这个接口不会走代理IP
> 应该是本地SSL Client证书的问题

解决了，重置本地的网络设置就可以了
