### ISSUE TITLE
 No module named 'requests'

### ISSUE THREAD

**Issue by sunjianfengHub** [jy03078584/hpv4g#7]
您好，我不会python，但是我需要您的成功，目前我遇到 No module named 'requests'这个问题，我本身是写web的，您可以帮助我逾越这个问题吗？我的系统是MacOS，环境是按照百度的方法安装的Py3

**Comment by jy03078584** [comment]
@sunjianfengHub 
Hi
这是`python`提示你本地没有安装`requests`这个第三方module.（和你`javascript`需要导包一个原理）
`requests`是一个python的第三方module 需要你安装 你可以google/baidu一下`python怎样安装第三方module`
一般的用`pip`安装即可

**Comment by sunjianfengHub** [comment]
好的，谢谢你的回复。我发现是因为mac自带py2.7，默认的包指向2.7的requests，而不是3的requests，因此报错。

**Comment by jy03078584** [comment]
done
