### ISSUE TITLE
能不能帮助给小孩约疫苗

### ISSUE THREAD

**Issue by liuxyon** [jy03078584/hpv4g#8]
我们这里正常疫苗预约都要抢, 能帮助制作个工具?

**Comment by jy03078584** [comment]
@liuxyon 
Hi  不好意思 因为疫苗平台太多了 不可能全部实现哈！
你可以搜搜看 **github** 上有没有你使用的疫苗平台脚本
或者可以考虑自己实现一个简单的 其实流程都差不多👏
